# Generated by Django 4.0.5 on 2022-07-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='*', unique=True, verbose_name='Número')),
                ('capacidade', models.IntegerField(help_text='*', verbose_name='Capacidade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ocupacao', models.BooleanField(default=False, verbose_name='Ocupação')),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criação')),
            ],
        ),
    ]
