# Generated by Django 4.0.5 on 2022-07-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_quarto_usuario_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarto',
            options={'verbose_name': 'Quarto', 'verbose_name_plural': 'Quartos'},
        ),
    ]
