# Generated by Django 4.0.5 on 2022-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_quarto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataChegada', models.DateTimeField(verbose_name='Data Chegada')),
                ('dataSaida', models.DateTimeField(verbose_name='Data Saída')),
                ('valorReserva', models.FloatField(verbose_name='Valor da Reserva')),
                ('pagamentoConfirmado', models.BooleanField(default=False, verbose_name='Pagamento COnfirmado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
