# Generated by Django 4.0.5 on 2022-07-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_pagamentoconfirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.quarto', verbose_name='Quarto'),
        ),
    ]
