# Generated by Django 4.0.5 on 2022-07-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valorReserva',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor da Reserva'),
        ),
    ]
