# Generated by Django 4.0.5 on 2022-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reserva_valorreserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataSaida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Saída'),
        ),
    ]
