# Generated by Django 4.0.5 on 2022-07-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_quarto_capacidade_alter_quarto_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.quarto', verbose_name='Quarto'),
        ),
    ]
