# Generated by Django 4.0.5 on 2022-07-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reservas', '0011_reserva_hospede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospede', verbose_name='Hóspede'),
        ),
    ]
