# Generated by Django 4.0.5 on 2022-07-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_reserva_hospede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataSaida',
            field=models.DateTimeField(blank=True, help_text='Disponível após pagamento confirmado', null=True, verbose_name='Data Saída'),
        ),
    ]
