# Generated by Django 4.0.5 on 2022-07-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_saida_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
