# Generated by Django 4.0.5 on 2022-07-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_pagamento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='observacoes',
        ),
    ]
