# Generated by Django 4.0.5 on 2022-07-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_options_alter_reserva_datasaida'),
        ('financeiro', '0005_remove_pagamento_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva', verbose_name='Reserva'),
        ),
    ]
