# Generated by Django 4.0.5 on 2022-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_pagamento_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='*Campo Obrigatório', max_digits=7, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='motivo',
            field=models.TextField(help_text='*Campo Obrigatório', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='*Campo Obrigatório', max_digits=7, verbose_name='Valor'),
        ),
    ]
