# Generated by Django 4.0.5 on 2022-07-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_alter_reserva_quarto'),
        ('financeiro', '0007_alter_pagamento_valor_alter_saida_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva', verbose_name='Reserva'),
        ),
    ]
