# Generated by Django 4.0.5 on 2023-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospede_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(help_text='*Campo Obrigatório', max_length=14, verbose_name='CPF'),
        ),
    ]
