# Generated by Django 4.0.5 on 2023-10-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hospede_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='datanascimento',
            field=models.DateField(default='1990-05-15', help_text='*Campo Obrigatório', verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
    ]
