# Generated by Django 4.0.5 on 2023-10-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospede_datanascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospede',
            name='datanascimento',
        ),
    ]
