# Generated by Django 4.0.5 on 2023-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_hospede_datanascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='dataNascimento',
            field=models.DateField(default='1990-05-05', help_text='*Campo Obrigatório', verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
    ]
